version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"  # Expose MySQL on local port 3306 for external access
    volumes:
      - mysql-data:/var/lib/mysql  # Persists MySQL data

volumes:
  mysql-data:
    driver: local